# Generated by Django 5.0.3 on 2024-04-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('title',), 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
