# Generated by Django 5.0.4 on 2024-04-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='current_version_indicator',
            field=models.BooleanField(default=False, verbose_name='признак текущей версии'),
        ),
    ]
